### ISSUE TITLE
Use with openhab-cloud?

### ISSUE THREAD

**Issue by Bl4d3s** [kenda/nextcloud-openhab#1]
Hi,

I can't figure out how to use this plugin with an openhab-cloud instance. The openhab instance is running in an private network, whereas the server running nextcloud is not in the same.

Is this even possible?

**Comment by kenda** [comment]
Hi,
Sorry for the late reply - somehow I missed a notification for your message :(

The scenario you provided should be possible. The plugin just calls the Openhab rest api which means you have to configure access on that side.
