### ISSUE TITLE
Add support for myopenhab.org

### ISSUE THREAD

**Issue by jandechent** [kenda/nextcloud-openhab#24]
Neither in the app, nor in the settings, can I set any server or credentials. So I cant use the app at all. Also there are no instructions in the app store. or did I just miss it?

**Comment by kenda** [comment]
You should be able to reach the settings via Settings -> Administration -> Additional settings -> Openhab viewer

Let me know if this works for you - cheers.

**Comment by jandechent** [comment]
Thanks, unfortunately I thought this works via myopenhab.org that doen't
seem to be the case. but this ticket can be closed.

Am Di., 4. Okt. 2022 um 19:40 Uhr schrieb Marcus Nitzschke <
***@***.***>:

**Comment by kenda** [comment]
I'm not really familiar with myopenhab.org but it seems to me that it should be also possible to access the API through myopenhab.org [1]. But this will need some adjustments to the app to be able to pass the user/password/token. I will keep this open and change the title accordingly.

[1] https://community.openhab.org/t/basic-usage-of-rest-api/126042/8

**Comment by martingwb** [comment]
> Neither in the app, nor in the settings, can I set any server or credentials. So I cant use the app at all. Also there are no instructions in the app store. or did I just miss it?

Same here for me on NC 24.0.5 while it worked in earlier versions of NC 24.
I can see this at the end of the "Additional settings" page html code:
`...
        <div class="bpm-result"></div>
    </form>
</div>
<div id="openhab" class="section"></div>

</div>
		</div>
		<div id="profiler-toolbar"></div>
	</body>
</html>
`
For some reason the <input> tags seem to be missing.

**Comment by kenda** [comment]
@martingwb I released 0.10.1 which should fix this issue. Please upgrade accordingly.
