### ISSUE TITLE
Support localization

### ISSUE THREAD

**Issue by p-bo** [kenda/nextcloud-openhab#25]
Hello,
Would it be possible to follow instructions on:
https://docs.nextcloud.com/server/latest/developer_manual/basics/front-end/l10n.html
...and make your app more accessible for non-English speakers please?

Thanks :-)

**Comment by kenda** [comment]
Hi,
Yes, definitely! Thanks for the suggestion - that was something that I totally missed from the beginning. I will try to implement this in the next days.

Cheers!

**Comment by p-bo** [comment]
Hi @kenda, many thanks for you attention to this!

Cheers!

**Comment by p-bo** [comment]
Strings is possible to translate on Transifex and translations are merged back into this repo - great and many thanks @kenda and @nickvergessen!
