### ISSUE TITLE
Analysing error message: No sitemaps found. Check your config or create a sitemap.

### ISSUE THREAD

**Issue by martingwb** [kenda/nextcloud-openhab#26]
Hi,
While I have configured sitemaps and do see them in the Android app NC (24.0.5) tells me that no sitemaps can be found.
Please let me know how/where to investigate this on my side. Nothing to be found in nextcloud.log or apache logs.
Thank you!

**Comment by kenda** [comment]
Hi,

hard to guess to be honest. Have you tried the "Ignore SSL issues?" checkbox? This can be helpful if you use self-signed certificates. Otherwise you could use curl to test the availability of the Openhab API in general.

Hope this helps a bit.

**Comment by martingwb** [comment]
Thank you, using curl helped to analyze and make it work.
Could it be that the "Ignore SSL issues?" is used in a counter intuitive way? I do see the sitemaps when being deactivated (checkbox is empty) only.

**Comment by kenda** [comment]
Hm, strange thing. It does work for me as expected and I was not able to find any "counter intuitive" implementation when having a quick look again. I would close here as it is working for you now. Please let me know, when you find any other hints. Thanks.
