### ISSUE TITLE
installation error in Nextcloud 18.0.

### ISSUE THREAD

**Issue by mccius03** [kenda/nextcloud-openhab#5]
When I try to install the APP Openhab Viewer  I will get the following error: "Certificate "4358" has been revoked"

**Comment by kenda** [comment]
This sounds like an issue with your certificate on Openhab side. Besides fixing that one, you could try the option to ignore ssl errors in the plugin config, maybe this helps.

**Comment by kenda** [comment]
Hi,
Indeed, there was an issue with the certificate. This is now fixed and you should be able to install the app again.

**Comment by mccius03** [comment]
Thank you, now it's runing
